<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>HMBSbige</Authors>
  </PropertyGroup>

  <PropertyGroup>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <OptimizationPreference>Size</OptimizationPreference>
    <PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="all" />
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>

  <!-- ReactiveUI.Binding exposes unrelated analyzer packages to consumers. -->
  <ItemGroup>
    <PrunePackageReference Include="Blazor.Common.Analyzers;Roslynator.Analyzers;SonarAnalyzer.CSharp" Version="114514.1919.810" />
  </ItemGroup>

  <Target Name="CleanPreviousPublish" BeforeTargets="PrepareForPublish" Condition="'$(AndroidApplication)' != 'true'">
    <RemoveDir Directories="$(PublishDir)" />
  </Target>

  <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
    <DebuggerSupport>false</DebuggerSupport>
    <DebugType>none</DebugType>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
  </PropertyGroup>

</Project>
