<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>NatTypeTester</AssemblyName>
    <ApplicationIcon>..\NatTypeTester.Views\Assets\icon.ico</ApplicationIcon>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PublishTrimmed)' == 'true'">
    <NoWarn>$(NoWarn);IL2046</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PublishAot)' == 'true'">
    <NoWarn>$(NoWarn);IL3051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="StaticLink.Avalonia" />
    <PackageReference Include="StaticLink.Avalonia.Native" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NatTypeTester.Views\NatTypeTester.Views.csproj" />
  </ItemGroup>

  <Target Name="ExcludeFilesFromPublish" AfterTargets="ComputeResolvedFilesToPublishList">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(Extension)' == '.pdb'" />
    </ItemGroup>
  </Target>

</Project>
