<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>NatTypeTester</AssemblyName>
    <ApplicationIcon>..\NatTypeTester.Views\Assets\icon.ico</ApplicationIcon>
    <PublishAot>true</PublishAot>
    <OptrisStaticGraphicsRequiredBackends>Vulkan;OpenGL;Software</OptrisStaticGraphicsRequiredBackends>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Optris.StaticGraphics.Avalonia.Vulkan" />
    <PackageReference Include="StaticLink.Avalonia.Native" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NatTypeTester.Views\NatTypeTester.Views.csproj" />
  </ItemGroup>

  <Target Name="ExcludeFilesFromPublish" AfterTargets="ComputeResolvedFilesToPublishList">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(Extension)' == '.pdb'" />
    </ItemGroup>
  </Target>

</Project>
