name: GitHub CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build
      run: msbuild -v:m -m -r -t:Build -p:Configuration=Release
